project_id = "grzvfzggmuamdxrzpasj"
[functions.generate-response]
enabled = true
verify_jwt = true
import_map = "./functions/generate-response/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-response/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-response/*.html" ]

[functions.generate-supportive-response]
enabled = true
verify_jwt = true
import_map = "./functions/generate-supportive-response/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-supportive-response/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-supportive-response/*.html" ]
